DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS comments;

CREATE TABLE images(
    id SERIAL PRIMARY KEY,
    url VARCHAR NOT NULL,
    username VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    comment_text VARCHAR NOT NULL,
    username VARCHAT NOT NULL,
    image_id SERIAL FOREIGN KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)


